# run "docker compose up" and tell fluent-bit to send data to port 9000:
#
#   fluent-bit -i cpu -o forward://127.0.0.1:9000
#
# it is also possible to send data via http through port 9010:
#
#   for i in $(seq 10); do curl -XPOST -H "Content-Type: application/json" -d '{"hello": "Calyptia'$i'"}' http://127.0.0.1:9010; sleep 1; done
#
# To inspect vivo exporter, use curl with `-i` to show headers:
#
#   curl -i http://127.0.0.1:2025/logs?from=0
version: '3'
services:
  vivo:
    image: calyptia/vivo
    ports:
      - "2025:2025"
      - "8000:3000"
      - "9000:24224"
      - "9010:9880"
