version: '3'
services:
  service:
    build:
      context: ./packages/service
      dockerfile: Dockerfile
    ports:
      - "9000:24224"
      - "9010:9880"
      - "2025:2025"
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    depends_on:
      - service
