version: "3.9"
services:
  app:
    image: flb-data-visualizer-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./:/home/node/code"
    ports:
      - "127.0.0.1:5489:5489"
      - "127.0.0.1:24224:24224"
