apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vivo
    app.kubernetes.io/instance: calyptia
  name: calyptia-vivo
spec:
  type: NodePort
  ports:
    - name: http
      port: 5489
      targetPort: 5489
    - name: forward
      port: 24224
      targetPort: 24224
  selector:
    app.kubernetes.io/name: vivo
    app.kubernetes.io/instance: calyptia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vivo
    app.kubernetes.io/instance: calyptia
  name: calyptia-internal-vivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vivo
      app.kubernetes.io/instance: calyptia
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vivo
        app.kubernetes.io/instance: calyptia
    spec:
      containers:
        - image: calyptia/vivo:1.1.0
          imagePullPolicy: Always
          name: vivo
          ports:
            - name: http-port
              containerPort: 5489
            - name: forward-port
              containerPort: 24224
          resources: {}
      restartPolicy: Always
