apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vivo
    app.kubernetes.io/instance: calyptia
  name: calyptia-vivo
spec:
  ports:
    - name: "5489"
      port: 5489
      targetPort: 5489
    - name: "24224"
      port: 24224
      targetPort: 24224
  selector:
    app.kubernetes.io/name: vivo
    app.kubernetes.io/instance: calyptia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vivo
    app.kubernetes.io/instance: calyptia
  name: calyptia-vivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vivo
      app.kubernetes.io/instance: calyptia
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vivo
        app.kubernetes.io/instance: calyptia
    spec:
      containers:
        - image: ghcr.io/calyptia/vivo
          name: vivo
          ports:
            - name: http-port
              containerPort: 5489
            - name: forward-port
              containerPort: 24224
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-port
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
          # We really should provide resource limits
          resources: {}
      restartPolicy: Always
