---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/name: vivo
    app.kubernetes.io/instance: calyptia
  name: calyptia-vivo
spec:
  ports:
    - name: "forward"
      port: 9000
      targetPort: 24224
    - name: "http"
      port: 9010
      targetPort: 9880
    - name: "vivo"
      port: 2025
      targetPort: 2025
    - name: "ui"
      port: 8000
      targetPort: 3000
    - name: "fluent-bit"
      port: 2020
      targetPort: 2020
  selector:
    app.kubernetes.io/name: vivo
    app.kubernetes.io/instance: calyptia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/name: vivo
    app.kubernetes.io/instance: calyptia
  name: calyptia-vivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vivo
      app.kubernetes.io/instance: calyptia
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vivo
        app.kubernetes.io/instance: calyptia
    spec:
      containers:
        - image: calyptia/vivo
          imagePullPolicy: Always
          name: vivo
          ports:
            - name: forward
              containerPort: 24224
            - name: http
              containerPort: 9880
            - name: vivo
              containerPort: 2025
            - name: fluent-bit
              containerPort: 2020
            - name: ui
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: fluent-bit
            failureThreshold: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: fluent-bit
            failureThreshold: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
