---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vivo-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/vivo"
        backend:
          service:
            name: calyptia-vivo
            port:
              number: 5489
      - pathType: Prefix
        path: "/forward"
        backend:
          service:
            name: calyptia-vivo
            port:
              number: 24224
