---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vivo-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        # The server makes a lot of assumptions about root URL so does not handle a prefix path well
        path: "/"
        backend:
          service:
            name: calyptia-vivo
            port:
              number: 5489
