---
name: Build containers and push a release on tag

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

jobs:
  build-container-images:
    outputs:
      digest: ${{ steps.docker_build.outputs.digest }}
    permissions:
      contents: read
      packages: write
    name: Build container images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata from Github
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          # Ensure we strip any 'v' prefix, provide a SHA and a latest tag only for default branch (master)
          tags: |
            type=semver,pattern={{version}},event=tag
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            # defaults for others
            type=schedule
            type=ref,event=branch
            type=ref,event=pr

      - name: Build the standard production image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
          load: false
          target: prod

      - name: Test build of the dev image
        uses: docker/build-push-action@v3
        with:
          tags: ignoreme
          platforms: linux/amd64
          push: false
          load: false
          target: dev

  test-container-images:
    name: Test container images
    needs:
      - build-container-images
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind
          config: ./kind/config.yaml

      - name: Apply local service using image from this run
        run: |
          sed -i 's|ghcr.io/calyptia/vivo|ghcr.io/calyptia/vivo@${{ needs.build-container-images.outputs.digest }}|g' ./vivo-k8s.yaml
          cat ./vivo-k8s.yaml
          kubectl apply -f ./vivo-k8s.yaml
        shell: bash

      - name: Check it is running ok
        timeout-minutes: 5
        run: |
          echo "Waiting for deployment to complete..."
          until kubectl rollout status deployment calyptia-vivo; do
            echo -n "."
            sleep 2
          done
          echo
          echo "Deployment completed successfully"
        shell: bash

      - name: Inject HTTP traffic
        timeout-minutes: 5
        run: |
          ./kind/setup-ingress.sh
          curl --verbose --fail -H 'Content-Type: application/json' -d '{"hello":"world!"}' http://localhost/flb/123456789
        shell: bash

      - name: Debug on failure
        continue-on-error: true
        if: failure()
        run: |
          kubectl cluster-info || true
          kubectl get all || true
          kubectl get events || true
          kubectl logs $(kubectl get pod --selector=app.kubernetes.io/name=vivo --output=jsonpath={.items..metadata.name}) || true
          kubectl -n ingress-nginx logs $(kubectl -n ingress-nginx get pod --selector=app.kubernetes.io/instance=ingress-nginx --output=jsonpath={.items..metadata.name}) || true
        shell: bash

      - name: Dump docker logs on failure
        continue-on-error: true
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: 'vivo,nginx'

  release-on-tag:
    if: startsWith(github.ref, 'refs/tags/')
    name: Create release
    needs:
      - build-container-images
      - test-container-images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release on tag
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
