---
name: Check for upstream releases to trigger update locally
on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  get-versions:
    name: Check upstream Fluent Bit and current branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      new-version: ${{ steps.fluent-bit-release-version.outputs.release }}
      new-major-version: ${{ steps.determine-major-version.outputs.replaced }}
      old-version: ${{ steps.lts-versions.outputs.fluent-bit-version }}
    steps:
      - id: fluent-bit-release-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: fluent
          repo: fluent-bit
          excludes: prerelease, draft

      - name: Determine major version tag
        id: determine-major-version
        uses: frabert/replace-string-action@v2.4
        with:
          pattern: '^(\d+\.\d+).*$'
          string: ${{ steps.fluent-bit-release-version.outputs.release }}
          replace-with: "$1"
          flags: "g"

      - uses: actions/checkout@v3

      - name: Get the current versions
        # Look for the default line in the Dockerfile
        id: lts-versions
        run: |
          DOCKERFILE_OSS_VERSION=$(grep "ARG FLUENT_BIT_VER" service/Dockerfile | cut -d '=' -s -f 2 -)
          echo "Using OSS version: $DOCKERFILE_OSS_VERSION"
          echo "fluent-bit-version=$DOCKERFILE_OSS_VERSION" >> $GITHUB_OUTPUT
        shell: bash

  set-versions:
    name: Run update and create PR
    needs:
      - get-versions
    if: needs.get-versions.outputs.new-major-version == '2.1' && needs.get-versions.outputs.new-version != needs.get-versions.outputs.old-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - run: |
          echo "${{ needs.get-versions.outputs.new-major-version }} == 2.1"
          echo "${{ needs.get-versions.outputs.new-version }} != ${{ needs.get-versions.outputs.old-version }}"
        shell: bash

      - uses: actions/checkout@v3

      - name: Run update version script
        run: |
          sed -i "s/$OLD_FLUENT_BIT_VERSION/$NEW_FLUENT_BIT_VERSION/g" service/Dockerfile
        shell: bash
        env:
          OLD_FLUENT_BIT_VERSION: ${{ needs.get-versions.outputs.old-version }}
          NEW_FLUENT_BIT_VERSION: ${{ needs.get-versions.outputs.new-version }}

      - name: Generate PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'dockerfile: update Fluent Bit release'
          signoff: true
          branch: ci_update_fluent_bit
          delete-branch: true
          title: 'dockerfile: update Fluent Bit release'
          labels: automerge,ci
